
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CalculationWorkerRole
{

using System;
    using System.Collections.Generic;
    
public partial class Position
{

    public string id { get; set; }

    public System.DateTimeOffset C__createdAt { get; set; }

    public Nullable<System.DateTimeOffset> C__updatedAt { get; set; }

    public byte[] C__version { get; set; }

    public string user_id { get; set; }

    public Nullable<double> latitude { get; set; }

    public Nullable<double> longitude { get; set; }

}

}
