//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationWorkerRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class satellites
    {
        public string id { get; set; }
        public System.DateTimeOffset C__createdAt { get; set; }
        public Nullable<System.DateTimeOffset> C__updatedAt { get; set; }
        public byte[] C__version { get; set; }
        public string name { get; set; }
        public string satellite_number { get; set; }
        public string international_designator { get; set; }
        public string epoch_date { get; set; }
        public string d_mean_motion { get; set; }
        public string dd_mean_motion { get; set; }
        public string drag_term { get; set; }
        public string ephemeris_type { get; set; }
        public string element_number { get; set; }
        public string inclination { get; set; }
        public string ascension { get; set; }
        public string eccentricity { get; set; }
        public string arg_of_perigee { get; set; }
        public string mean_anomaly { get; set; }
        public string mean_motion { get; set; }
        public string revolution_number { get; set; }
    }
}
